### ISSUE TITLE
the spotlight regex format not clear

### ISSUE THREAD

**Issue by kimusan** [carlonluca/logcat-colorize#3]
I was trying to mark multiple words using thre spotlight regex. 
My normal approach would be -s "foo|bar|baz" but that does not seem to work.
It looks like you are using the perl regex format (default in boost) but the boost_regex_replace seems to not allow this in the way you use it. 

It been a while since i used the bloated boost lib, but I recall something about adding the following arguments to regex_replace: "boost::match_default | boost::format_all";

This might solve the problem

**Comment by kimusan** [comment]
turns out it was because I was trying to mark the "name" (like bt_stack) which is not passed through the spotlight filter. So this would be a request to make it possible to mark certain apps/processes in the logcat log.

**Comment by carlonluca** [comment]
If you want, you can test the latest version. It should include what you asked.

**Comment by carlonluca** [comment]
It seems to be done. Re-open if needed.
