### ISSUE TITLE
Disable buffering in egrep

### ISSUE THREAD

**Issue by antonysigma** [carlonluca/logcat-colorize#4]
I like the idea of filtering the `adb logcat` streams with `egrep`, but I often get unresponsive output when it is in turn piped to `logcat-colorize`. Could you add the following line in `README.md` to disable grep buffering?

```bash
 # Piping to grep for regex filtering (much better than adb filter):
    $ adb logcat -v time | egrep --line-buffering -i '(sensor|wifi)' | logcat-colorize
```

FYI, here is the link to a similar issue on Stackoverflow:
https://stackoverflow.com/a/7162898/706334

**Comment by carlonluca** [comment]
Hello,
what OS are we talking about?
I typically pipe logcat-colorize to grep or egrep. Would that be ok?

**Comment by antonysigma** [comment]
I am using Ubuntu Linux. Piping the output the other way around work for me. Thank you.
