### ISSUE TITLE
After switching timezone. The time displayed by logcat is still the previous time zone

### ISSUE THREAD

**Issue by GccBoy** [carlonluca/logcat-colorize#6]
![image](https://github.com/carlonluca/logcat-colorize/assets/63889850/abb58a73-0410-445d-861c-5e81d51635ac)

**Comment by carlonluca** [comment]
The date is not provided by logcat-colorize but from Android. For me, changing the time zone also changes the date and time of the logs.

**Comment by GccBoy** [comment]
thanks your replay
